#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
TOTAL_MINUTES=7

# 这个向导写的是 JSON 配置，不是 .env。把 ENV_FILE 指到 /dev/null，
# 让库里的 ask/ask_secret 不再去 .env 里找默认值（-f 判定会直接失败）。
ENV_FILE=/dev/null
NOTIFY_CONFIG="${NOTIFY_CONFIG:-$HOME/.config/notify-telegram-cli/config.json}"
PROXY=""
BOT_USERNAME=""
CHAT_ID=""

# ── helpers ───────────────────────────────────────────────────────────────

_backup_existing_config() {
  [[ -f "$NOTIFY_CONFIG" ]] || return 0
  local bak="$NOTIFY_CONFIG.bak-$(date +%Y%m%d-%H%M%S)"
  cp -p "$NOTIFY_CONFIG" "$bak"
  chmod 600 "$bak" 2>/dev/null || true
  note "已备份原配置 → $bak"
}

# write_notify_config TOKEN CHAT_ID PROXY — 原子写入 mode 600 的 JSON。
# 值经环境变量传给 python，不进 argv，因此不会出现在 ps 输出里。
write_notify_config() {
  mkdir -p "$(dirname "$NOTIFY_CONFIG")"
  chmod 700 "$(dirname "$NOTIFY_CONFIG")"
  ( umask 077
    NOTIFY_CFG_PATH="$NOTIFY_CONFIG" \
    NOTIFY_CFG_TOKEN="$1" \
    NOTIFY_CFG_CHAT_ID="$2" \
    NOTIFY_CFG_PROXY="$3" \
    python3 <<'PY'
import json, os
path = os.environ["NOTIFY_CFG_PATH"]
data = {}
if os.path.exists(path):
    try:
        with open(path, encoding="utf-8") as fh:
            existing = json.load(fh)
        if isinstance(existing, dict):
            data = existing
    except Exception:
        data = {}
data.update({
    "bot_token": os.environ["NOTIFY_CFG_TOKEN"],
    "chat_id": os.environ["NOTIFY_CFG_CHAT_ID"],
    "proxy_url": os.environ["NOTIFY_CFG_PROXY"],
})
tmp = path + ".tmp"
with open(tmp, "w", encoding="utf-8") as fh:
    json.dump(data, fh, indent=2)
    fh.write("\n")
os.chmod(tmp, 0o600)
os.replace(tmp, path)
PY
  )
  printf '  %s✓ wrote%s %s (mode 600)\n' "$GREEN" "$RESET" "$NOTIFY_CONFIG"
}

# 只探测「能不能到 api.telegram.org」，不碰任何凭据。
_probe_proxy() {
  NOTIFY_PROBE_PROXY="$1" python3 <<'PY'
import os, sys, urllib.error, urllib.request
proxy = os.environ.get("NOTIFY_PROBE_PROXY", "").strip()
if proxy.lower() in {"none", "direct"}:
    proxy = ""
handlers = [urllib.request.ProxyHandler({"http": proxy, "https": proxy})] if proxy \
    else [urllib.request.ProxyHandler({})]
opener = urllib.request.build_opener(*handlers)
try:
    opener.open("https://api.telegram.org/", timeout=20)
except urllib.error.HTTPError as exc:
    print("OK|reachable (HTTP %s)" % exc.code); sys.exit(0)
except Exception as exc:
    print("ERR|%s" % exc); sys.exit(1)
print("OK|reachable")
PY
}

# getMe → 校验 token 是否有效
_tg_verify_token() {
  NOTIFY_TOKEN="$1" NOTIFY_PROXY_URL="$2" python3 <<'PY'
import json, os, sys, urllib.request
token = os.environ["NOTIFY_TOKEN"]
proxy = os.environ.get("NOTIFY_PROXY_URL", "").strip()
if proxy.lower() in {"none", "direct"}:
    proxy = ""
handlers = [urllib.request.ProxyHandler({"http": proxy, "https": proxy})] if proxy \
    else [urllib.request.ProxyHandler({})]
opener = urllib.request.build_opener(*handlers)
try:
    with opener.open("https://api.telegram.org/bot%s/getMe" % token, timeout=25) as response:
        payload = json.load(response)
except Exception as exc:
    print("ERR|%s" % exc); sys.exit(1)
if not payload.get("ok"):
    print("ERR|%s" % payload.get("description", "unknown error")); sys.exit(1)
result = payload["result"]
print("OK|%s|%s" % (result.get("username", "?"), result.get("first_name", "")))
PY
}

# 轮询 getUpdates，抓最近一条消息所在的 chat
_tg_discover_chat() {
  NOTIFY_TOKEN="$1" NOTIFY_PROXY_URL="$2" python3 <<'PY'
import json, os, sys, time, urllib.request
token = os.environ["NOTIFY_TOKEN"]
proxy = os.environ.get("NOTIFY_PROXY_URL", "").strip()
if proxy.lower() in {"none", "direct"}:
    proxy = ""
handlers = [urllib.request.ProxyHandler({"http": proxy, "https": proxy})] if proxy \
    else [urllib.request.ProxyHandler({})]
opener = urllib.request.build_opener(*handlers)
url = "https://api.telegram.org/bot%s/getUpdates?limit=100&timeout=0" % token
found = None
for attempt in range(10):
    if attempt:
        time.sleep(6)
    try:
        with opener.open(url, timeout=30) as response:
            payload = json.load(response)
    except Exception as exc:
        print("ERR|%s" % exc); sys.exit(1)
    if not payload.get("ok"):
        print("ERR|%s" % payload.get("description", "getUpdates failed")); sys.exit(1)
    for update in payload.get("result", []):
        for key in ("message", "edited_message", "channel_post"):
            chat = (update.get(key) or {}).get("chat") or {}
            if chat.get("id") is not None:
                label = chat.get("username") or chat.get("title") or chat.get("first_name") or ""
                found = (str(chat["id"]), chat.get("type", "?"), str(label))
    if found:
        break
if not found:
    print("NONE|"); sys.exit(2)
print("OK|%s|%s|%s" % found)
PY
}

# ── stages ────────────────────────────────────────────────────────────────

banner "Telegram 通知通道 · 配置向导"

stage "确认代理" 1
say "Telegram API 在这里需要走代理。向导用它访问 api.telegram.org，不需要时填 none。"
DETECTED_PROXY="${TELEGRAM_PROXY_URL:-${https_proxy:-${HTTPS_PROXY:-http://172.26.176.1:7890}}}"
note "检测到：$DETECTED_PROXY"
PROXY_INPUT=""
ask PROXY_INPUT "代理地址（回车采用检测值）:"
PROXY="${PROXY_INPUT:-$DETECTED_PROXY}"
step "探测 api.telegram.org…"
probe="$(_probe_proxy "$PROXY" || true)"
case "$probe" in
  OK\|*) note "${probe#OK|}" ;;
  *) warn "连不上：${probe#ERR|}"
     warn "检查代理是否在跑，或换个地址重跑向导。"
     exit 1 ;;
esac

stage "创建 Bot 并拿到 token" 2
say "在 BotFather 里建一个属于你的 bot。全程在 Telegram 内操作。"
open_url "https://t.me/BotFather"
step "点 Start，或发送 /start"
step "发送 /newbot"
step "起一个显示名（随便，中文也行）"
step "起一个 username，必须以 bot 结尾且全 Telegram 唯一，例如 etsuya_notify_bot"
step "BotFather 回一段含 token 的消息，形如 123456789:AAH…，复制整串"
note "token 等同于这个 bot 的密码。输入不回显，也不会进入本对话记录。"
ask_secret NOTIFY_TOKEN "粘贴 token:"
if [[ ! "$NOTIFY_TOKEN" =~ ^[0-9]{6,}:[A-Za-z0-9_-]{30,}$ ]]; then
  warn "格式不对，应为 <数字>:<约 35 位字符串>。检查是否多复制了空格或漏了字符。"
  exit 1
fi
step "向 Telegram 验证 token…"
verify="$(_tg_verify_token "$NOTIFY_TOKEN" "$PROXY" || true)"
case "$verify" in
  OK\|*) IFS='|' read -r _ BOT_USERNAME BOT_NAME <<<"$verify"
         printf '  %s✓%s token 有效 → @%s（%s）\n' "$GREEN" "$RESET" "$BOT_USERNAME" "$BOT_NAME" ;;
  *)     warn "验证失败：${verify#ERR|}"
         warn "token 可能复制错了。重跑向导，或去 BotFather 用 /mybots → API Token 重取。"
         exit 1 ;;
esac

stage "捕获 chat_id" 1
say "bot 得知道往哪个会话发。你先主动给它发一条消息。"
step "在 Telegram 搜索上一步的 username：@${BOT_USERNAME}"
step "打开对话，随便发一句，例如 /start 或 hi"
note "向导每 6 秒轮询一次 getUpdates，最多约 1 分钟。发完等着就行。"
discovered="$(_tg_discover_chat "$NOTIFY_TOKEN" "$PROXY" || true)"
case "$discovered" in
  OK\|*) IFS='|' read -r _ CHAT_ID CHAT_TYPE CHAT_LABEL <<<"$discovered"
         printf '  %s✓%s 捕获到 chat_id=%s（%s，%s）\n' "$GREEN" "$RESET" "$CHAT_ID" "$CHAT_TYPE" "$CHAT_LABEL" ;;
  NONE\|*) warn "没等到消息。确认你是给 @${BOT_USERNAME} 发的，然后重跑向导。"
           exit 1 ;;
  *)       warn "查询失败：${discovered#ERR|}"
           warn "若提示 webhook，说明这个 bot 已设过 webhook，删掉后才能用 getUpdates。"
           exit 1 ;;
esac

stage "写入配置并发送测试" 3
_backup_existing_config
write_notify_config "$NOTIFY_TOKEN" "$CHAT_ID" "$PROXY"
note "已把 token、chat_id、代理写进配置，之后不依赖任何环境变量。"
step "复检配置与连通性…"
TELEGRAM_PROXY_URL="$PROXY" notify --doctor || true
step "发送测试消息…"
if TELEGRAM_PROXY_URL="$PROXY" notify --title "通知通道已打通" \
     "$(printf '配置完成。\n\n- bot: @%s\n- chat: %s\n- 代理: %s\n\n以后我会用这条通道推送进展、失败和需要你决策的事。' \
       "$BOT_USERNAME" "$CHAT_ID" "$PROXY")"; then
  printf '  %s✓%s 已发送\n' "$GREEN" "$RESET"
else
  warn "发送失败。看上面的报错；常见原因是代理中途掉了或 chat_id 不对。"
fi
pause "看一眼 Telegram，确认收到了吗？"

SKIPPED+=("让 agent 主动用这条通道：对 DSH 说「发消息告诉我…」，notify-telegram skill 会自动触发")

finish
